[tool.poetry]
name = "desdeo-brb"
version = "0.1.0"
description = ""
authors = ["Giovanni Misitano <giovanni.a.misitano@jyu.fi>"]

[tool.poetry.dependencies]
python = "^3.7"
scipy = "^1.3.1"
numpy = "^1.17.2"
flake8 = "^3.7.8"
black = "^19.3b0"
isort = "^4.3.21"
matplotlib = "^3.1.1"
pandas = "^0.25.1"
jupyter = "^1.0"
numba = "^0.46.0"
sklearn = "^0.0.0"
numdifftools = "^0.9.39"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
